---
title: "Going Long on Temperature"
author: "Simon Crase"
date: "27 October 2016"
output: html_document
---
```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(knitr)
source('timeseries.R')
# Set n.records to -1 to process the entire dataset, 0r 10000 for testing
n.records=100000
# Number of stations
n.stations=25
```

# Idea

Many people do not accept that global are rising. While some of them are naïve, others are shrewd investors. I wondered what would happen if these folk thought about the temperature the way they think of investments.

The Sharpe Ratio is an important tool for judging a stock: $\frac{\mu}{\sigma}$

# Methodology

* Select stations at random

# Results

```{r,echo=FALSE}
station.index<-read.index()
temperature.readings<-read.temperatures(n=n.records)
ids<-get.random.stations.with.data(n.stations,station.index,temperature.readings)
rownames(station.index)<-station.index$ID
ss<-subset(station.index[ids,],TRUE,c('ID','NAME','LATITUDE','LONGITUDE'))
kable(ss,row.names=FALSE)
for (id in ids){
  dd<-get.data.for.station(id,temperature.readings)
  dd<-attach.average.temperature(dd)
  name<-station.index[station.index$ID==id,5]
  x<-dd$YEAR
  y<-dd$MEAN
  plot(x=x,y=y,main=paste(id,name,sep=': '),xlab = "Year", ylab="Average T")
  abline(lm(y~x), col="red")
}
```
